* 二，基本概念
** 纽扣电池: 纽扣电池是低功耗蓝牙的主要设计目标。
** 能量即时间：时间即能量是贯穿低功耗蓝牙设计的另一个基本概念
鲁棒的设备发现要求至少有两个设备：一个用于寻找其他设备，一个或多个设备则处于可发现状态。
在低功耗蓝牙中，一个设备如果想被发现就必须每隔几秒发送三次短消息。

数据报文的长度很短，主要是下面3个原因：
1) 发送相同数据减少能量消耗。
2) 控制器消除了在一次数据传输中需要不断校准无线电的需求。由于无线电模块在传送或接受时不断发热，将改变硅芯片的特性，并因此改变传输频率。
   如果报文控制在较短的长度，则芯片没有足够的时间发热。
3) 短期、间歇性而非长期的取电令设备可以从一个纽扣电池获得更多的能量。
** 昂贵的内存
** 非对称设计
假如一个设备只有发射器，另一个设备只有接收器，则二者构成的网络成为非对称网络。
发射器只完成最基本的功能，大部分复杂的功能运算都交给接收器。
** 为成功而设计
** 凡事皆有状态
** 客户端-服务器架构
** 模块化架构
基于通用属性规范的模块化的服务器架构，允许设备以标准的方式将原子的、可封装的行为比特装进单个服务并将其公开。
** 十亿只是个小数目
** 无连接模型
** 范式
1. 客户端-服务器架构
2. 面向服务的架构

*** 客户端-服务器架构
客户端通过网络想服务器发送请求，服务器回复响应。二者分工明确，当系统的不同部分位于不同的设备上时，这种划分必不可少。
*** 面向服务的架构
客户端-服务器架构之上的进一步抽象，将服务器中的信息组织成服务的模型。
该服务可以被发现，进行交互和用做已知的语义。这意味着改服务具有确定的行为，在给定相同的条件时，总会产生同样的结果。
服务具有一套规则和惯例：
1. 正式合约
   一个服务之所以被视为服务，是因为其在公开的功能以及如何工作两个方面提供正规的描述。
2. 松耦合
   在面向对象的软件中，单独的系统组件是被设计成无边界效应的独立对象。那些发生在组件之间的相互作用可以被明确地定义和测试。
   将依赖关系减少到最低限度，使修改服务的实现时不会带来意想不到的边界效应，从而降低风险。
3. 抽象化
4. 可重用性
5. 无状态
   为了让众多的客户端支持服务扩展，服务器不能保存任何客户端的状态数据。
6. 可组合型
7. 自治
8. 可发现性
   要想使用服务就必须能够发现服务。
   低功耗蓝牙采用的方法：使用同一个协议实现服务发现以及服务交互。
   
